### ISSUE TITLE
Fast(er) Sync at Startup

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#2]
It seems that some of the functions previously carried out by the plugin are now done by the server and only removed items are tracked.
The routines responsible for the 'fastsync' are here in Emby for Kodi.
https://github.com/MediaBrowser/plugin.video.emby/blob/4f9d2d54315a52e8764b43dd97576876e7c89113/resources/lib/library.py#L542

and here
https://github.com/MediaBrowser/plugin.video.emby/blob/4f9d2d54315a52e8764b43dd97576876e7c89113/libraries/emby/core/api.py#L332

**Comment by Long-Man** [comment]
I should add that this applies to resume after screensaver. It appears as if the server sees the client as offline when Kodi's screensaver is activated and online when the screensaver is deactivated.

**Comment by Montellese** [comment]
I have implemented fast synchronization using a combination of what Emby server provides and the Kodi companion plugin. It reduces synchronization in case of no or very few changes by a factor of ~15. Now synchronizing 800 already imported movies takes around 5 - 10 seconds instead of ~100 seconds.

But I'm facing an issue with Emby server throwing an exception when trying to activate fast synchronization for userdata (playcount, ...) changes, see https://emby.media/community/index.php?/topic/81857-sqliteexception-on-items-when-using-mindatelastsavedforuser/. I'm waiting for Luke's feedback before I can merge it.

**Comment by Long-Man** [comment]
Are you getting the error with Jellyfiin as well?

**Comment by Montellese** [comment]
> Are you getting the error with Jellyfiin as well?

Thanks for the hint. I gave it a try and noticed that the communication with the Kodi Companion plugin is a bit different for Jellyfin so I fixed that.

And now everything also seems to work on Emby.

The last issue open now is that currently the timestamp I pass is a local timestamp and Kodi companion expects a UTC timestamp. I just need to figure out how to determine the timezone used by Kodi...

**Comment by Montellese** [comment]
I fixed the last issue and made some detailed tests.

* working
  * added items are correctly retrieved from Emby directly
  * items with changed metadata (e.g. title or plot) are correctly retrieved from Emby directly
  * removed items are correctly retrieved from Kodi companion (not supported by Emby)
* not working
  * items with changed user data (watched / unwatched, resume point, ...) are not correctly retrieved from Emby directly. They simply don't appear in the list.

@angelblue05: is this supposed to work or am I doing something wrong? I read in the changelog of Kodi companion that `UserDataChanged` isn't populated anymore because it is supported by Emby directly. I can confirm that `UserDataChanged` is empty but Emby doesn't list the items as changed either.

**Comment by Montellese** [comment]
I also just noticed that this brings a problem with it. Without fast sync any changes to the media provider or import settings are automatically applied during the next synchronization.
But with fast sync if the user e.g. disables Direct Play support after a previous synchronization the add-on will only perform a fast sync and the change in the settings will not take effect.

Now the question is how best to solve this. A few ideas:

1. always perform a full sync after having changed any setting. This might result in unnecessary full syncs because some unrelated setting was changed.
2. provide an option in the settings to force a full sync. This might not be intuitive because the user has to remember to trigger this option manually.
3. provide a "force full synchronization" context item on media providers and imports. This might also not be intuitive because the user has to remember to trigger this manually.
4. let the add-on somehow cache the synchronization relevant setting values and compare them before performing a synchronization. if nothing has changed do a fast sync otherwise force a full sync.

**Comment by Long-Man** [comment]
A similar problem exists with Emby for Kodi. If one switches from Native (Addon) to Direct play, a database reset is required. I would suggest provide the option and prompt the user to do the re sync.

**Comment by Long-Man** [comment]
@Montellese , 
Can you provide some details for Luke here,

https://emby.media/community/index.php?/topic/82258-retrieving-changeset-when-client-returns-online-mediaimport/

**Comment by Montellese** [comment]
So the issue with getting all changed items since a specified point in the past has been solved. Now I only need to solve detecing re-synchronization after changing certain settings.

**Comment by Long-Man** [comment]
Sweet. I haven't gotten any reports of problems on the Emby or Jellyfin forums. Mostly when will this be in master. One request for a tvOS build if possible with Jenkins.
