### ISSUE TITLE
Add No Password Option

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#40]
It is fairly common in the community to have clients only on LAN or  if external, coming via via VPN. In such cases, many consider it relatively safe to to not have a password for each user.

**Comment by Montellese** [comment]
I checked the code and getting it to work without passwords is as easy as removing three lines of code. The question is whether we should make it this easy or not.

There are probably three cases to consider:
1. Local access with a manually specified user: In this case we can either just provide a password field which can be empty or not or we can provide a switch to explicitely specify that there is no password. The latter would be a bit more explicit.
2. Local access with a user selected from the list: In this case Emby would actually tell us whether the user has a password set or not. So we could hide the password field if the user doesn't have a password set anyway. That would improve the user experience a bit. But it would require some additional code in the add-on interface to facilitate this kind of responsive behaviour of the settings.
3. Emby Connect: This doesn't require a password at all because the login / access happens through the PIN login feature.

**Comment by Long-Man** [comment]
1. Emby for Kodi has the box for the password and allows sign in with it empty if there is no password. I would say implement the easiest. The switch would nice but it would also tempt someone to check if there is a password.
2. I don't think there is a need to hide the password field. The user should know if a password is needed. BTW Jellyfin has reversed that setting in the server which automatically makes each newly added user publicly listed. The default is hidden; one has to choose for each user to be visible.
